[package]
name = "magma"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.33.7"
image = "0.25.10"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0"
vulkano = "0.35.2"
vulkano-shaders = "0.35.0"
vulkano-win = "0.34.0"
winit = "0.30.13"

[profile.dev]
opt-level = 1
